title: Bahaghari Maps # your name (or website title) here
logo: "/images/3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bahaghari Maps aims to create usable trail maps for fellow outdoor enthusiasts in the Philippines.
  <br><br>
  <a href="https://www.facebook.com/bahagharimaps"><i class="fa-brands fa-facebook-square"></i></a>
  <a href="https://www.instagram.com/bahaghari.maps"><i class="fa-brands fa-instagram-square"></i></a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
